trigger:
- main

pool:
  name: Default

steps:
- task: Docker@2
  displayName: 'Docker login'
  inputs:
    command: 'login'
    containerRegistry: 'dev01conn'  # Use the name of your Azure DevOps service connection

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'dev01conn'  # Use the name of your Azure DevOps service connection
    repository: 'flask-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'  # Path to the Dockerfile in the repository
    tags: '$(Build.BuildId)'

- script: |
    sudo docker run -d -p 5000:5000 dev01.azurecr.io/flask-app:$(Build.BuildId)
  displayName: 'Deploy Docker image to self-hosted agent'