trigger:
- master

pool:
  name: Default

stages:
- stage: Developer
  displayName: 'Developer Environment'
  jobs:
  - job: Build_and_Deploy_Developer
    displayName: 'Build and Deploy to Developer'
    steps:
    - task: Docker@2
      displayName: 'Docker login'
      inputs:
        command: 'login'
        containerRegistry: 'dev01conn'

    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        containerRegistry: 'dev01conn'
        repository: 'flask-app-developer'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.SourceBranchName)-$(Build.BuildId)'

    - script: |
        CONTAINER_NAME="flask-app-container-developer"
        sudo docker stop "$CONTAINER_NAME" || true
        sudo docker rm "$CONTAINER_NAME" || true
        sudo docker run -d -p 5000:5000 --name "$CONTAINER_NAME" dev01.azurecr.io/flask-app-developer:$(Build.SourceBranchName)-$(Build.BuildId)
      displayName: 'Deploy Docker image to Developer Environment'

- stage: Staging
  displayName: 'Staging Environment'
  dependsOn: Developer
  condition: succeeded('Developer')
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Staging'
    pool:
      vmImage: 'ubuntu-20.04'
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ManualValidation@1
            displayName: 'Manual Approval for Staging Deployment'
            inputs:
              instructions: 'Please approve the deployment to Staging.'

          - script: |
              CONTAINER_NAME="flask-app-container-staging"
              sudo docker stop "$CONTAINER_NAME" || true
              sudo docker rm "$CONTAINER_NAME" || true
              sudo docker run -d -p 5010:5000 --name "$CONTAINER_NAME" dev01.azurecr.io/flask-app-developer:$(Build.SourceBranchName)-$(Build.BuildId)
            displayName: 'Deploy Docker image to Staging Environment'

- stage: Production
  displayName: 'Production Environment'
  dependsOn: Staging
  condition: succeeded('Staging')
  jobs:
  - job: Build_and_Deploy_Production
    displayName: 'Build and Deploy to Production'
    steps:
    - task: ManualValidation@1
      displayName: 'Manual Approval for Production Deployment'
      inputs:
        instructions: 'Please approve the deployment to Production.'

    - script: |
        CONTAINER_NAME="flask-app-container-production"
        sudo docker stop "$CONTAINER_NAME" || true
        sudo docker rm "$CONTAINER_NAME" || true
        sudo docker run -d -p 5050:5000 --name "$CONTAINER_NAME" dev01.azurecr.io/flask-app-developer:$(Build.SourceBranchName)-$(Build.BuildId)
      displayName: 'Deploy Docker image to Production Environment'
