trigger:
- main

pool:
  name: Default

steps:
- task: Docker@2
  displayName: 'Docker login'
  inputs:
    command: 'login'
    containerRegistry: 'dev01conn'  # Use the name of your Azure DevOps service connection

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'dev01conn'  # Use the name of your Azure DevOps service connection
    repository: 'flask-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'  # Path to the Dockerfile in the repository
    tags: '$(Build.SourceBranchName:refs/heads/=/)-$(Build.BuildId)'  # Replace slashes with underscores

- script: |
    # Define a name for the container
    CONTAINER_NAME="flask-app-container"
    
    # Stop and remove the container if it exists
    sudo docker stop "$CONTAINER_NAME" || true
    sudo docker rm "$CONTAINER_NAME" || true
    
    # Run the container with the specified name
    sudo docker run -d -p 5000:5000 --name "$CONTAINER_NAME" dev01.azurecr.io/flask-app:$(Build.SourceBranchName:refs/heads/=/)-$(Build.BuildId)
  displayName: 'Deploy Docker image to self-hosted agent'